### ISSUE TITLE
sudo mkdir -r /root/.aqemu

### ISSUE THREAD

**Issue by IcyonGit** [3kh0/Windows-on-Codespaces#1]
![Screenshot 2023-09-11 2 32 32 PM](https://github.com/3kh0/Windows-on-Codespaces/assets/100136502/00714de8-b93c-4352-908f-69d1bf7b7883)

**Comment by clarinetandmonkey** [comment]
same

**Comment by PSYclownYT** [comment]
same

**Comment by PSYclownYT** [comment]
why are you doing this on school chromebook

**Comment by Mollomm1** [comment]
fixed https://codeberg.org/Mollomm1/W10-On-Github-Codespaces/src/branch/main

3kh0, just need to update this repo.

**Comment by 3kh0** [comment]
Done
